version: '2.2'

services:
  podsync:
    container_name: podsync
    image: mxpv/podsync:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./data:/app/data/
      - ./config.toml:/app/config.toml
